#!/bin/bash

set -e # exit on error

SCRIPT=$(readlink -f "$0")
TLB_DIR=$(dirname "$SCRIPT")
IMG_DIR=/media/usb0
CRON_DIR=/etc/cron.d
INPUT=/dev/video0
PLAY_SOUND=true

function capture () {
	local DATE=$(date +"%Y-%m-%d_%H%M")
	local MINOFFSET=$[ $(date +"%-M") % 5 ]
	local PID=$(fuser $INPUT)
	if [ "$PID" ]; then
		# there's a problem with the previous process so kill it
		kill -9 $PID
		sleep 5
	fi
	fswebcam --device $INPUT --resolution 1280x960 --delay 1 --skip 15 --jpeg 85 --quiet "$IMG_DIR/$DATE.jpg"
	if [ $PLAY_SOUND ]; then
		aplay --quiet "$TLB_DIR/blip.wav"
	fi
}

function start () {
	sed -e "s@__SCRIPT_PATH__@$SCRIPT@" "$TLB_DIR/crontab" > "$CRON_DIR/timelapsebot"
}

function stop () {
	rm "$CRON_DIR/timelapsebot"
}

function reloadModules () {
	sudo modprobe -r uvcvideo
	sudo modprobe uvcvideo
	echo "Reloaded modules"
}

if [[ $1 =~ ^(start|stop|capture)$ ]]; then
	"$@"
else
	echo "\
  _______                __                         ____        __ 
 /_  __(_)___ ___  ___  / /___ _____  ________     / __ )____  / /_
  / / / / __ \`__ \\/ _ \\/ / __ \`/ __ \\/ ___/ _ \\   / __  / __ \\/ __/
 / / / / / / / / /  __/ / /_/ / /_/ (__  )  __/  / /_/ / /_/ / /_  
/_/ /_/_/ /_/ /_/\___/_/\__,_/ .___/____/\___/  /_____/\____/\__/  
                            /_/                                    
Run as root!

tlb <command>

Commands:
	start		add a cron job to take a photo every minute
	stop		remove cron job
	capture		take a photo"
fi
