#!/bin/bash

set -e # exit on error

IMG_DIR=/media/usb0
INPUT=/dev/video0
PLAY_SOUND=true

function capture () {
	local DATE=$(date +"%Y-%m-%d_%H%M")
	local MINOFFSET=$[ $(date +"%-M") % 5 ]
	local PID=$(fuser $INPUT)
	if [ "$PID" ]; then
		# there's a problem with the previous process so kill it
		kill -9 $PID
		sleep 5
	fi
	fswebcam --device $INPUT --resolution 1280x960 --jpeg 85 --quiet "$IMG_DIR/$DATE.jpg"
	if [ $PLAY_SOUND ]; then
		play_sound
	fi
}

function preview () {
	capture
	pcmanfm $(find $IMG_DIR -type f | tail -n 1)
}

function start () {
	systemctl start timelapsebot.timer
}

function stop () {
	systemctl stop timelapsebot.timer
}

function play_sound () {
	openssl base64 -d <<SOUND | aplay --quiet
UklGRsQnAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YaAnAAAAAOki
6SLNMc0x1jrWOilAKUBrQmtCzEHMQUM+Qz57N3s3cSxxLIUYhRj13/Xfbc9tzz3F
PcXNvs2+2LvYu9i72LvXvNe8y8HLwRDKEMoE1wTX5PHk8RolGiUmMyYzyzvLO9xA
3EDoQuhCHEIcQmg+aD53N3c3Piw+LO0X7ReI34jfOs86zzHFMcXmvua+2LvYu9i7
2LtuvW69msKawi7LLsu32LfYE/wT/OIm4iZENEQ0kzyTPGhBaEFCQ0JDSEJIQmk+
aT5KN0o31yvXK+QW5BbY3tje387fzgbFBsXlvuW+2LvYu9i72Lvuve69UsNSwzLM
MsxR2lHamwybDGQoZCg4NTg1PD08PddB10GBQ4FDWkJaQk4+Tj7+Nv42SCtIK3gV
eBX+3f7daM5ozsbExsTRvtG+4rviu9i72Ltevl6++cP5wyXNJc3b29vbOBE4EbQp
tCkPNg82zD3MPTJCMkKsQ6xDWUJZQh8+Hz6bNps2myqbKqkTqRMK3Qrd4M3gzXjE
eMSyvrK+7bvtu/S79LvEvsS+lcSVxAzODM5g3WDdeBR4FOEq4SrPNs82Sz5LPn1C
fULJQ8lDSUJJQuE94T0mNiY21CnUKWoRahEI3AjcTc1NzSDEIMSKvoq+8rvyuyS8
JLwjvyO/KsUqxe3O7c7l3uXeEBcQF/Qr9Ct/N383vT69Pr1CvULbQ9tDLkIuQpc9
lz2kNaQ1+Sj5KJAOkA7/2v/as8yzzMPDw8Nevl6+8rvyu1C8ULx+v36/vMW8xcvP
y89y4HLgRBlEGfIs8iwiOCI4JT8lP/NC80LkQ+RDCkIKQkM9Qz0VNRU1DCgMKJoK
mgr22fbZF8wXzGTDZMMvvi++8Lvwu3q8erzXv9e/TMZMxqjQqNAN4g3iMxszG+Et
4S28OLw4hD+EPyJDIkPmQ+ZD30HfQec85zx+NH40DycPJ5X9lf3v2O/Yect5ywPD
A8P/vf+97bvtu6O8o7wvwC/A28bbxofRh9G747vj8hzyHMQuxC5NOU053T/dP0tD
S0PiQ+JDrkGuQYU8hTzeM94zAiYCJvH08fTs1+zX3MrcyqLCosLPvc+96rvqu828
zbyIwIjAbMdsx2rSatKD5YPljB6MHpwvnC/XOdc5MEAwQG9Db0PZQ9lDeEF4QR08
HTw2MzYz5yTnJO3w7fDv1u/WQcpBykPCQ8KgvaC96Lvou/e897ziwOLA/8f/x1DT
UNNv52/nCCAIIGswazBbOls6fkB+QI5DjkPMQ8xDPkE+QbA7sDuIMogyvCO8I+Ht
4e331ffVqMmoyeXB5cFzvXO957vnuyO9I70+wT7BlMiUyDzUPNSK6YrpbSFtITIx
MjHbOts6yEDIQKpDqkO7Q7tD/0D/QD47PjvTMdMxgSKBIlfrV+sG1QbVEskSyYrB
isFIvUi96Lvou1G9Ub2cwZzBLMksyS/VL9Xn6+frviK+IvMx8zFVO1U7DkEOQcJD
wkOnQ6dDvUC9QMg6yDoXMRcxNiE2IR7pHukc1BzUgMiAyDDBMMEevR697Lvsu4K9
gr39wf3ByMnIySnWKdal7qXu/iP+I60yrTLLO8s7UUFRQddD10OPQ49Dd0B3QE06
TTpWMFYw1x/XHyDnIOc50znT8Mfwx9rA2sD3vPe88bvxu7S9tL1gwmDCZ8pnyivX
K9cH8gfyLyUvJWEzYTM9PD08kEGQQehD6EN0Q3RDLUAtQM85zzmOL44vYx5jHk3l
TeVb0lvSZcdlx4bAhsDTvNO8+rv6u+m96b3GwsbCC8sLyzXYNdjj9uP2UiZSJhA0
EDSsPKw8zEHMQfZD9kNWQ1ZD4D/gP0w5TDm/Lr8u1xzXHJ7jnuOF0YXR3cbdxjXA
NcCxvLG8BLwEvCG+Ib4wwzDDs8uzy0rZStn7BvsGaidqJ7o0ujQWPRY9BEIEQgFE
AUQ1QzVDkD+QP8U4xTjqLeotLRstGwziDOK00LTQWMZYxue/57+SvJK8EbwRvFy+
XL6cw5zDX8xfzGraatrMDMwMdyh3KF41XjV9PX09OkI6QgpECkQQQxBDPT89Pzo4
OjgOLQ4tYRlhGZLgkuDpz+nP2MXYxZy/nL91vHW8IbwhvJm+mb4MxAzEEc0RzZXb
ldtxEHEQeyl7Kf41/jXhPeE9bUJtQg9ED0TpQulC5j7mPqs3qzcrLCssaBdoFy3f
Ld8kzyTPWsVaxVS/VL9bvFu8NLw0vNm+2b6AxIDEx83Hzc7cztxNE00TdSp1Kpo2
mjZBPkE+nEKcQhJEEkS/Qr9CjD6MPhg3GDdAK0ArNhU2Fdrd2t1kzmTO4cThxA6/
Dr9EvES8SbxJvBy/HL/2xPbEgs6CzhbeFt65FbkVZytnKzE3MTeePp4+yULJQhJE
EkSSQpJCLz4vPoE2gTZNKk0qsxKzEpbcltyqzarNa8RrxMy+zL4wvDC8YbxhvGK/
Yr9xxXHFQ89Dz27fbt/aF9oXUSxRLMQ3xDf4Pvg+80LzQg9ED0RjQmNCzz3PPeU1
5TVSKVIpsw+zD2LbYtv1zPXM+MP4w42+jb4evB68fLx8vKu/q7/vxe/FCtAK0Nng
2eDGGcYZMy0zLVM4UzhOP04/GUMZQwlECUQwQjBCaz1rPUU1RTVNKE0oxAvECzra
OtpFzEXMicOJw1C+UL4PvA+8mbyZvPe/979wxnDG1tDW0FviW+KJG4kbDi4OLt44
3jiiP6I/PUM9QwFEAUT6QfpBBD0EPaA0oDQ/Jz8nagRqBB7ZHtmZy5nLHsMewxe+
F74DvAO8ury6vEfAR8D2xvbGqdGp0ffj9+MrHSsd4y7jLmU5ZTnyP/I/X0NfQ/VD
9UPCQcJBmjyaPPcz9zMmJiYmkfWR9QzYDNjzyvPKtcK1wuC94L36u/q73bzdvJnA
mcB/x3/HgtKC0rLlsuWyHrIesi+yL+g56Dk/QD9AfUN9Q+dD50OGQYZBLDwsPEgz
SDMBJQElOvE68QXXBddRylHKUMJQwqy9rL3zu/O7A70Dve7A7sANyA3IYtNi05Pn
k+ciICIgejB6MGg6aDqJQIlAmEOYQ9ZD1kNIQUhBuzu7O5UylTLQI9AjDe4N7gfW
B9azybPJ78HvwXy9fL3vu++7LL0svUfBR8GeyJ7ISdRJ1Kfpp+l/IX8hPTE9MeM6
4zrQQNBAsUOxQ8JDwkMGQQZBRjtGO9wx3DGQIpAicetx6xHVEdUayRrJkMGQwU69
Tr3uu+67V71XvaLBosEzyTPJOdU51f7r/uvKIsoi+jH6MVs7WzsUQRRBx0PHQ6xD
rEPCQMJAzTrNOh4xHjFBIUEhL+kv6STUJNSFyIXINcE1wSO9I73wu/C7hr2GvQHC
AcLNyc3JMNYw1rnuue4GJAYksjKyMtA70DtVQVVB2kPaQ5NDk0N6QHpAUTpROlsw
WzDfH98fKucq5z7TPtP0x/TH3cDdwPq8+rz0u/S7t723vWPCY8JrymvKMNcw1xny
GfI0JTQlZTNlM0A8QDyTQZNB6kPqQ3dDd0MwQDBA0jnSOZEvkS9pHmkeVeVV5V/S
X9Jox2jHiMCIwNW81bz8u/y7673rvcnCycIOyw7LOdg52Pn2+fZWJlYmEjQSNK48
rjzOQc5B+EP4Q1hDWEPiP+I/TjlOOcIuwi7bHNsco+Oj44fRh9Hfxt/GN8A3wLO8
s7wGvAa8I74jvjHDMcO1y7XLTdlN2REHEQdtJ20nuzS7NBg9GD0GQgZCA0QDRDZD
NkOSP5I/xzjHOOwt7C0xGzEbD+IP4rbQttBaxlrG6L/ov5O8k7wSvBK8Xb5dvp7D
nsNhzGHMbNps2tQM1Ax5KHkoYDVgNX89fz07QjtCC0QLRBFDEUM+Pz4/Ozg7OBAt
EC1kGWQZlOCU4OrP6s/ZxdnFnb+dv3a8drwivCK8mr6avg3EDcQSzRLNl9uX23UQ
dRB8KXwp/zX/NeI94j1tQm1CEEQQROpC6kLnPuc+rDesNywsLCxrF2sXLt8u3yXP
Jc9bxVvFVL9Uv1y8XLw0vDS82r7avoDEgMTIzcjNz9zP3E8TTxN2KnYqmzabNkI+
Qj5uQm5CtEO0QzRCNELePd49WDZYNosqiyrQFNAUm96b3p/Pn8+DxoPGCMEIwYS+
hL66vrq+osGiwW3Hbce40LjQst+y36IUohQYKRgpGTQZNOw67DqmPqY+qD+oPw8+
Dz7JOck5fDJ8Mg8nDyc3ETcRhd+F3/vR+9G1ybXJycTJxJ/Cn8IAwwDD6cXpxYnL
ict91H3UBuMG4yYVJhUnJycnGDEYMTw3PDeCOoI6QztDO5g5mDlsNWw1aS5pLnIj
ciNrDWsN1ODU4LfUt9RMzUzN78jvyB7HHsemx6bHhsqGyu7P7s912HXYbeZt5hMV
ExXNJM0kqS2pLRkzGTPtNe01cDZwNrk0uTS0MLQwDSoNKqsfqx81CTUJmOKY4uvX
69dg0WDRmM2YzR7MHszIzMjMlc+Vz7LUstSz3LPc7ent6WYUZhTwIfAhrymvKWMu
Yy7AMMAwCDEIMU4vTi+BK4ErTiVOJakbqRsaAxoD7OTs5Lrbutsd1h3W79Lv0s/R
z9GV0pXSQtVC1f7Z/tlU4VThku2S7QwTDBNnHmce9CT0JOAo4CjAKsAqzirOKhsp
GymYJZgl/B/8H0sXSxev+a/5AegB6GbgZuDN283bSdlJ2YfYh9hl2WXZ4Nvg2xzg
HOCS5pLmcfFx8dIQ0hDeGd4ZFB8UHxwiHCJwI3AjQSNBI6AhoCGDHoMesBmwGU4S
ThLK+Mr4QuxC7H3mfeYZ4xnjX+Ff4QzhDOEA4gDiNuQ25MLnwucA7QDtyvXK9TAN
MA2CE4ITBxcHF+cY5xiAGYAZ/Rj9GHQXdBfmFOYUNBE0EdIL0gtE+kT6C/ML89vv
2+9J7knu2e3Z7VTuVO6Y75jvjvGO8Sn0KfRz93P3F/wX/BEFEQX/Bf8FAAAAAAAA
SOUND
}

if [[ $1 =~ ^(start|stop|capture|preview)$ ]]; then
	"$@"
else
	echo "\
  _______                __                         ____        __ 
 /_  __(_)___ ___  ___  / /___ _____  ________     / __ )____  / /_
  / / / / __ \`__ \\/ _ \\/ / __ \`/ __ \\/ ___/ _ \\   / __  / __ \\/ __/
 / / / / / / / / /  __/ / /_/ / /_/ (__  )  __/  / /_/ / /_/ / /_  
/_/ /_/_/ /_/ /_/\___/_/\__,_/ .___/____/\___/  /_____/\____/\__/  
                            /_/                                    
Run as root!

tlb <command>

Commands:
	start		take a photo every minute
	stop		stop timer
	preview		capture and open image
	capture		take a photo"
fi
